# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  test-ios:
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install any dependencies
    - name: Install dependencies
      run: swift package resolve

    # Run tests on iPhone 14 Simulator with iOS 17.5
    - name: Run Tests on iPhone 14 Simulator (iOS 17.5)
      run: |
        xcodebuild clean build test \
          -scheme 'OpenWeather' \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.5' \
          -enableCodeCoverage YES \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=NO \
          EXCLUDED_ARCHS=arm64
          
  # build:

  #   runs-on: macos-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build
  #     run: swift build -v
  #   - name: Run tests
  #     run: swift test -v
