# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  test-ios:
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    
      
    - name: Build and test
      run: |
        xcodebuild clean build test -scheme 'OpenWeather' \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' build \
          -allowProvisioningUpdates

    # Run tests on iPhone 14 Simulator with iOS 16.2
    # - name: Run Tests on iPhone 14 Simulator (iOS 16.2)
    #   run: |
    #     xcodebuild test \
    #       -scheme 'OpenWeather' \
    #       -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' \
    #       -enableCodeCoverage YES \
    #       -allowProvisioningUpdates
          
    
