# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  test-ios:
    runs-on: macos-latest
    env:
      SCHEME: 'OpenWeather'

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # # Install any dependencies
    # - name: Install dependencies
    #   run: swift package resolve

    - name: Select Xcode Version 
      run: sudo xcode-select -s /Applications/Xcode_15.4.app
      
    # Build the project
    - name: Build Project for scheme  ${{ env.SCHEME }}
      run: |
        xcodebuild clean build \
          -scheme ${{ env.SCHEME }} \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=NO \
          EXCLUDED_ARCHS=arm64 \
          > /dev/null 2>&1


    # Run tests on iPhone 15 Simulator with iOS 17.5
    - name: Run Tests on iPhone 15 Simulator (iOS 17.5) for scheme  ${{ env.SCHEME }}
      run: |
        xcodebuild test \
          -scheme  ${{ env.SCHEME }} \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
          -only-testing:OpenWeatherTests \
          -enableCodeCoverage YES \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=NO \
          EXCLUDED_ARCHS=arm64
          
  # build:

  #   runs-on: macos-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build
  #     run: swift build -v
  #   - name: Run tests
  #     run: swift test -v
